from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor, white
import datetime
import textwrap

PAGE_WIDTH, PAGE_HEIGHT = A4
def ensure_space(c, y, min_space=140):
    """
    Ensures there is enough vertical space before drawing content.
    If not, creates a new page and resets layout.
    """
    if y < min_space:
        c.showPage()

        # Redraw background
        c.setFillColor(HexColor("#020617"))
        c.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, fill=1, stroke=0)
        left_accent_bar(c)

        return PAGE_HEIGHT - 80
    return y

# =================================================
# HELPERS
# =================================================
def footer(c, page_no):
    c.setStrokeColor(HexColor("#1f2937"))
    c.line(40, 55, PAGE_WIDTH - 40, 55)

    c.setFont("Helvetica", 9)
    c.setFillColor(HexColor("#9ca3af"))
    c.drawString(40, 40, "Generated by LegalInspect AI • Confidential SME Report")
    c.drawRightString(PAGE_WIDTH - 40, 40, f"Page {page_no}")


def left_accent_bar(c):
    c.setFillColor(HexColor("#7c3aed"))
    c.rect(0, 0, 10, PAGE_HEIGHT, fill=1, stroke=0)


def section_title(c, text, y):
    c.setFont("Helvetica-Bold", 14)
    c.setFillColor(white)
    c.drawString(40, y, text)
    c.setStrokeColor(HexColor("#374151"))
    c.line(40, y - 6, PAGE_WIDTH - 40, y - 6)
    return y - 26


def paragraph(c, text, x, y, width=95, size=10):
    c.setFont("Helvetica", size)
    c.setFillColor(white)
    for line in textwrap.wrap(text, width):
        c.drawString(x, y, line)
        y -= size + 3
    return y


def card(c, x, y, w, h, bg):
    c.setFillColor(bg)
    c.roundRect(x, y, w, h, 14, fill=1, stroke=0)


def kpi(c, x, y, title, value, bg):
    card(c, x, y, 150, 56, bg)
    c.setFont("Helvetica-Bold", 20)
    c.setFillColor(white)
    c.drawCentredString(x + 75, y + 30, str(value))
    c.setFont("Helvetica", 9)
    c.drawCentredString(x + 75, y + 10, title)


# =================================================
# MAIN PDF
# =================================================
def generate_pdf_report(
    contract_type,
    entities,
    clause_df,
    aggregate,
    decision,
    missing_clauses
):
    filename = "AI_Contract_Risk_Report.pdf"
    c = canvas.Canvas(filename, pagesize=A4)

    # COLORS
    bg = HexColor("#020617")
    card_bg = HexColor("#0f172a")
    purple = HexColor("#7c3aed")
    green = HexColor("#22c55e")
    yellow = HexColor("#f59e0b")
    red = HexColor("#dc2626")
    muted = HexColor("#9ca3af")

    # BACKGROUND
    c.setFillColor(bg)
    c.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, fill=1, stroke=0)
    left_accent_bar(c)

    # HEADER
    card(c, 14, PAGE_HEIGHT - 120, PAGE_WIDTH, 120, card_bg)

    c.setFont("Helvetica-Bold", 24)
    c.setFillColor(white)
    c.drawString(40, PAGE_HEIGHT - 55, "AI Contract Risk Report")

    c.setFont("Helvetica", 12)
    c.setFillColor(muted)
    c.drawString(40, PAGE_HEIGHT - 80, "Advanced Legal Risk Intelligence")

    c.setFont("Helvetica", 9)
    c.drawRightString(
        PAGE_WIDTH - 40,
        PAGE_HEIGHT - 55,
        datetime.datetime.now().strftime("%d %b %Y")
    )

    y = PAGE_HEIGHT - 150

    # =================================================
    # 1. CONTRACT OVERVIEW
    # =================================================
    y = section_title(c, "1. Contract Overview", y)

    c.setFont("Helvetica-Bold", 11)
    c.setFillColor(white)
    c.drawString(40, y, f"Contract Type: {contract_type}")
    y -= 18

    # ---- START CONTENT TRACK
    start_y = y

    # TEMP TEXT PASS (to calculate height)
    temp_y = y - 20
    for section, values in entities.items():
        if not values:
            continue
        temp_y -= 14  # section title
        for v in values:
            temp_y -= 14 * (len(v) // 90 + 1)
        temp_y -= 10

    card_height = start_y - temp_y + 16

    # ---- DRAW CARD (AUTO HEIGHT)
    card(c, 40, start_y - card_height, PAGE_WIDTH - 80, card_height, card_bg)

    # ---- DRAW CONTENT
    ty = start_y - 20

    for section, values in entities.items():
        if not values:
            continue

        c.setFont("Helvetica-Bold", 10)
        c.setFillColor(purple)
        c.drawString(55, ty, section)
        ty -= 14

        c.setFont("Helvetica", 9)
        c.setFillColor(white)
        for v in values:
            ty = paragraph(c, f"• {v}", 60, ty)
        ty -= 10

    # ---- MOVE Y BELOW CARD (CRITICAL FIX)
    y = start_y - card_height - 30
    # =================================================
    # 2. RISK DASHBOARD
    # =================================================
    y = section_title(c, "2. Risk Dashboard", y)

    kpi(c, 40, y - 60, "Total Risk Score", aggregate["total_risk_score"], purple)
    kpi(c, 210, y - 60, "High Risk Clauses", aggregate["high_risk_count"], red)
    kpi(c, 380, y - 60, "Medium Risk Clauses", aggregate["medium_risk_count"], yellow)

    y -= 90

    # =================================================
    # 3. FINAL AI DECISION
    # =================================================
    y = section_title(c, "3. Final AI Decision", y)

    card(c, 40, y - 60, PAGE_WIDTH - 80, 60, green)

    c.setFont("Helvetica-Bold", 14)
    c.setFillColor(white)
    c.drawString(55, y - 32, "Sign After Changes")

    c.setFont("Helvetica", 10)
    c.drawString(
        55,
        y - 48,
        "The contract contains one or more medium-risk clauses. These clauses should be revised or clarified before signing."
    )

    y -= 90

    # =================================================
    # 4. MISSING CLAUSES
    # =================================================
    y = section_title(c, "4. Missing Clauses", y)

    c.setFont("Helvetica", 10)
    c.setFillColor(red)
    for m in missing_clauses:
        c.drawString(55, y, f"• {m}")
        y -= 14

    y -= 20

    # =================================================
    # 5. HIGH RISK CLAUSE SUMMARY
    # =================================================
    y = ensure_space(c, y, min_space=160)
    y = section_title(c, "5. High Risk Clause Summary", y)  

    risky = clause_df[clause_df["Risk"].isin(["High", "Medium"])].head(5)
    c.setFont("Helvetica", 10)
    c.setFillColor(white)

    for _, row in risky.iterrows():
        y = paragraph(
            c,
            f"Clause {row['Clause ID']} ({row['Risk']}): {row['Reasons']}",
            55,
            y
        )

    # FOOTER
    footer(c, 1)
    c.save()

    return filename
